# Generated by Django 2.0 on 2017-12-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('active', models.BooleanField()),
                ('dateFinished', models.DateField(blank=True)),
            ],
        ),
    ]
