# Generated by Django 2.0 on 2017-12-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
