# Generated by Django 2.0 on 2017-12-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateFinished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
